import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import PokemonCard from '@/components/card';
import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence, AnimateSharedLayout } from 'framer-motion';
import BiggerCard from '@/components/BiggerCard';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [index, setIndex] = useState(false);

  const handleClose = useCallback(() => {
    setIndex(false);
  }, []);
  const [nfts, setNfts] = useState([
    'https://i.guim.co.uk/img/media/ef8492feb3715ed4de705727d9f513c168a8b196/37_0_1125_675/master/1125.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=d456a2af571d980d8b2985472c262b31',
    'https://www.cnet.com/a/img/resize/e547a2e4388fcc5ab560f821ac170a59b9fb0143/hub/2021/12/13/d319cda7-1ddd-4855-ac55-9dcd9ce0f6eb/unnamed.png?auto=webp&fit=crop&height=1200&width=1200',
    'https://imageio.forbes.com/specials-images/imageserve/6170e01f8d7639b95a7f2eeb/Sotheby-s-NFT-Natively-Digital-1-2-sale-Bored-Ape-Yacht-Club--8817-by-Yuga-Labs/0x0.png?format=png&width=960'
  ]);
  const [selectedId, setSelectedId] = useState(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AnimateSharedLayout type='crossfade'>
        <main className={styles.main}>
          {nfts.length > 0
            ? nfts.map(item => (
                <div onClick={() => setSelectedId(item)}>
                  <PokemonCard
                    key={`${item}`}
                    cardId={item}
                    shouldHover={!selectedId ? true : false}
                    url={item}
                  />
                </div>
              ))
            : null}
          <AnimatePresence>
            {selectedId ? (
              <BiggerCard
                onClick={setSelectedId}
                id={selectedId}
                shouldHover={true}
                url={selectedId}
              />
            ) : null}
          </AnimatePresence>
        </main>
      </AnimateSharedLayout>
    </>
  );
}
